const jobs = [
  {
    Id: 1,
    Title: "Chief Human Resource Office",
    EmpType: "Full time, permanent  or contract",
    DirectReport: "Chief Executive Officer ",
    ProfileWithinOrg: "Member of senior leadership team",
    Location: "Nairobi, Kenya ",
    RoleDetails: [
      "Our client, a reputable financial institution within the region, is looking for a forward-thinking and experienced individual to lead its people transformation agenda as the Chief Human Resources Officer (or Human Resource Lead, whichever is preferred).",
      "The ideal candidate will be experienced in driving transformation from a people, organization and culture perspective and will be a strategic leader vast in the use of data and analytics to support decision-making relating to assigned portfolio.",
      "Reporting to the Chief Executive Officer, the CHRO will provide strategic leadership for all people-related initiatives critical to enabling the organisation achieve its objectives.",
      "The role holder will be a member of the senior leadership team and will be responsible for developing and overseeing the implementation of leading practice people management strategies, policies and programmes to drive a strong employee experience for about 1000 staff and promote productivity",
    ],
    Responsibilities: [
      "Develop and ensure implementation of a people management strategyfor the organization that is aligned to the objectives and highlydynamic priorities of the organization.",
      "Ensure the development and consistent implementation of leading practice frameworks and processes to guide attraction, development, effective deployment and retention of the requisite skill set for the organization. These frameworks include but are not limited to resourcing, performance and career management, leadership development, employee relations, reward management, etc.",
      "Ensure the above strategies are cascaded into actionable work plans, policies, processes and programmes and also ensure that these are in line with applicable labour laws.",
      "Serve as a strategic business partner to management and other leaders in the organization to ensure consistent implementation of agreed people management policies.",
      "Stay abreast of applicable leading practices relating to themes that impact productivity, employee engagement, culture alignment, etc. and make recommendations to the CEO on how these affect the deliverables of the HR department.",
      "Provide leadership to the entire human resource department to ensure provision of best-in-class services to the organization. Take responsibility for ensuring that the organization’s operating structure and culture continuously enable the delivery of strategic objectives.",
      "Place strategic focus on succession planning and create and maintain a process for continuous strengthening of leadership capacity within the organization.",
      "As a member of the leadership team, serve as a role model for the core values of the organization to peers, assigned staff as well as all stakeholder groups. ",
      "Ensure effective use of relevant data and supporting technology in the delivery of HR services to the organization.",
      "Provide people-related insights to the organization and ensure these are effectively leveraged to improve productivity and employee engagement.",
      "Perform other duties as assigned by the CEO in line with agreed delegation matrix.",
    ],
    AcademicQualifications: [
      "A Bachelor’s degree in the humanities, social sciences, or human resource management.",
      "A Master’s degree in strategic human resource management, organization development, business administration, etc. from a reputable institution will be an added advantage.",
      "Membership with relevant local, regional or global professional bodies is required.",
    ],
    ExperienceRequirements: [
      "Ten to fifteen years’ experience in strategic human resource management in dynamic and complex organizational environment is key.",
      "At least five years in career history must be in a similar role in terms of scale and complexity.",
    ],
    Competencies: [
      "Demonstrable knowledge of and exposure to all aspects of human resource management along the employee lifecycle.",
      "Broad knowledge and experience in resourcing, organization development, change management, employee experience, reward management, learning and leadership development, etc.",
      "Understanding of applicable laws and regulations.",
      "Ability to effectively leverage data to present insights.",
      "Familiarity with leading practice ERP solutions, particularly is it relates to people management.",
    ],
    Behaviours: [
      "Professionalism and integrity in line with organisation values",
      "Planning and organization",
      "Strategic thinking skills",
      "Commercial acumen",
      "Communication and interpersonal skills",
      "Ability to effectively manage multiple stakeholders",
      "Tact and diplomacy",
      "Ability to manage and drive change.",
    ],
    Contacts: [
      {
        Id: 1,
        JobId: 1,
        Name: "Brian D’Souza",
        Telephone: "+254 (0) 709 576 132",
        Email: "briandesouza@kpmg.co.ke",
      },
      {
        Id: 2,
        JobId: 1,
        Name: "Associate Director, Transformation - People and Change",
        Telephone: "+254 (0) 709 576 688",
        Email: "titilopeolajide@kpmg.co.ke",
      },
      {
        Id: 3,
        JobId: 1,
        Name: "Hilda Amahundu",
        Telephone: "+254 (0) 709 576 448",
        Email: "hamahundu@kpmg.co.ke",
      },
    ],
  },
  {
    Id: 2,
    Title: "Director, Banking and Payment Operations",
    EmpType: "Full time, permanent or contract",
    DirectReport: "Chief Executive Officer or Deputy Chief Executive Officer",
    ProfileWithinOrg: "Member of senior leadership team",
    Location: "Nairobi, Kenya",
    RoleDetails: [
      "Our client, a reputable financial institution within the region, is looking for a forward-thinking and experienced individual to lead its Banking and Payment Operations department.",
      "The ideal candidate will be an experienced banker with extensive understanding of and exposure to leading practice (technology and data enabled) front and back office bank operations, controls as well as digital payment systems.",
      "Reporting to the Chief Executive Officer/ Deputy Chief Executive Office, the Director of Banking and Payment Operations will provide strategic leadership for all banking and payment-related processes, including clearing and settlement systems, so as to enable the organization achieve its objectives.",
      "The role holder will be a member of the senior leadership team and will be responsible for developing and overseeing the implementation of leading practice strategies, policies, and initiatives within assigned portfolio to ensure the provision of excellent services to the bank’s institutional customers and clients.",
    ],
    Responsibilities: [
      "Ensure development and implementation of strategies to ensure continuous optimization of banking and payment operations processes to drive effective and efficient services to the Bank’s customers.",
      "Ensure the organization effectively delivers on its role to all its institutional and wholesale customers by providing them with effective banking services, cash management services and supporting operations.",
      "Institute processes and policies relating to banking and payment operations.",
      "Ensure the above strategies are cascaded into actionable work plans for own department and also ensure that these are in compliance with applicable laws and regulations.",
      "Collaborate with relevant departments within the organization to review organization-wide policies particularly those that are customer facing and those that have an impact on banking and payment operations.Exciting career opportunity",
      "Play a proactive role in the development and strengthening of relationships with customers by providing effective and efficient back office services.",
      "Oversee the implementation of the bank’s banking and payment operations initiatives across the region.",
      "Provide the required leadership and support to enable the payments team implement an integrated system to facilitate the electronic submission and processing of payment returns.",
      "Provide oversight to ensure that the banking and payment operations framework is implemented throughout the organization.",
      "Provide adequate oversight of the banking and payment operations systems to ensure compliance within the existing legal and regulatory framework.",
      "Proactively review the banking and payment product service providers and ensure that approval of new products is undertaken in a timely manner in order to promote an all-inclusive, technologically- driven payment landscape.",
      "Continuously monitor the effectiveness of banking operations and implement improvements as approved by management and the board.",
      "Stay abreast of applicable leading practices relating to the management of banking and payment operations and ensure continuous up-skilling of team members.",
      "Perform other duties as assigned by the CEO or Deputy CEO in line with agreed delegation matrix.",
    ],
    AcademicQualifications: [
      "A Bachelor’s degree in economics, banking and finance, accounting, finance, business administration, computer science or any other relevant discipline.",
      "A Master’s degree in any of the above disciplines from a reputable institution will be an added advantage.",
      "Membership with relevant local, regional or global professional bodies is required.",
    ],
    ExperienceRequirements: [
      "Ten to fifteen years’ experience in banking operations or payment systems in dynamic and complex organizational environment is key.",
      "At least five years in career history must be in a similar role in terms of scale and complexity.",
    ],
    Competencies: [
      "Demonstrable knowledge of and exposure to all aspects of banking operations (i.e. front office and back office operations, payment systems operation, etc.)",
      "Understanding of applicable laws and regulations.",
      "Knowledge of and experience using core banking systems.",
      "Experience working with large scale institutional clients.",
      "Deep knowledge of risks and controls with respect to banking operations and payment systems.",
      "Ability to effectively leverage data to present insights and optimize banking and payments processes.",
      "Customer relationship management.",
    ],
    Behaviours: [
      "Professionalism and integrity in line with organization values",
      "Planning and organization",
      "Strategic thinking skills",
      "Commercial acumen",
      "Communication and interpersonal skills",
      "Ability to effectively manage multiple stakeholders",
      "Tact and diplomacy",
      "Ability to manage and drive change.",
    ],
    Contacts: [
      {
        Id: 1,
        JobId: 1,
        Name: "Brian D’Souza",
        Telephone: "+254 (0) 709 576 132",
        Email: "briandesouza@kpmg.co.ke",
      },
      {
        Id: 2,
        JobId: 1,
        Name: "Associate Director, Transformation - People and Change",
        Telephone: "+254 (0) 709 576 688",
        Email: "titilopeolajide@kpmg.co.ke",
      },
      {
        Id: 3,
        JobId: 1,
        Name: "Hilda Amahundu",
        Telephone: "+254 (0) 709 576 448",
        Email: "hamahundu@kpmg.co.ke",
      },
    ],
  },
  {
    Id: 3,
    Title: "Head, Back Office Operations – Banking",
    EmpType: "Full time, permanent or contract",
    DirectReport: "Director, Banking and Payment Operations",
    ProfileWithinOrg: "Member of senior leadership team",
    Location: "Nairobi, Kenya",
    RoleDetails: [
      "Our client, a reputable financial institution within the region, is looking for a forward-thinking and experienced individual for the role of Head, Back Office Operations – Banking.",
      "The ideal candidate will be an experienced banker with extensive experience in back office operations, transactions management, treasury operations, electronic banking, institutional banking and client relationship management.",
      "The ideal candidate will also have good experience leveraging technology and data to improve transactions processing.",
      "Reporting to the Director, Banking and Payment Operations, the role holder will provide strategic leadership for all back office related activities so as to enable the organisation achieve its objectives relating to oversight of payment processing, treasury operations, internet banking, reconciliations, etc.",
      "The role holder will be a senior member of the organisation and will be responsible for ensuring the seamless running of the back office operations.",
      "They will also lead the implementation of leading back office operations strategies, policies and programmes.",
    ],
    Responsibilities: [
      "Develop and drive implementation of leading practice back office operations strategies and processes with an actionable plan to enable the organization deliver on its objectives to its customers, in line with applicable laws and regulations.",
      "Ensure the organization provides effective banking services, cash management services and other relevant support to its institutional clients in line with the mandate of the organization.",
      "Ensure that a mechanism is in place to optimize electronic banking services to customers by liaising with relevant departments within the organization to improve efficiency of service delivery.",
      "Take responsibility for successful planning, implementation and testing of new services and initiatives within assigned portfolio.",
      "Collaborate across multiple departments to review bank-wide policies and decisions that have a direct impact on back office operations.",
      "Take responsibility for building staff capability within the division to ensure performance targets are met whilst continually maintaining all risk, quality, regulatory and procedural standards.",
      "Provide support to the Director, Banking and Payment Operations in effective running of the wider department.",
      "Periodically conduct a benchmarking of key performance metrics for back office operations to articulate improvement areas and drive efficiency within the division. This needs to be done with a view towards better leverage of technology and data.",
      "Perform other duties as assigned by the Director, Banking and Payment Operations in line with agreed delegation matrix.",
    ],
    AcademicQualifications: [
      "A Bachelor’s degree in economics, banking and finance, accounting, finance, business administration, computer science or any other relevant discipline.",
      "A Master’s degree in any of the above disciplines from a reputable institution will be an added advantage.",
      "Membership with relevant local, regional or global professional bodies is required.",
    ],
    ExperienceRequirements: [
      "Eight to twelve years’ experience in banking operations or payment systems in dynamic and complex organizational environment is key.",
      "At least three years in career history must be in a similar role in terms of scale and complexity.",
    ],
    Competencies: [
      "Demonstrable knowledge of and exposure to all aspects of banking operations, particularly back office operations, payment systems operation, etc.",
      "Understanding of applicable laws and regulations.",
      "Knowledge of and experience using core banking systems.",
      "Experience working with large scale institutional clients.",
      "Deep knowledge of risks and controls with respect to banking operations and payment systems.",
      "Ability to effectively leverage data to present insights and optimize banking and payment processes.",
      "Customer relationship management.",
      "Professionalism and integrity in line with organisation values",
      "Planning and organization",
      "Strategic thinking skills",
      "Commercial  acumen",
      "Communication and interpersonal skills",
      "Ability to effectively manage multiple stakeholders",
      "Tact and diplomacy",
      "Ability to manage and drive change.",
    ],
    Behaviours: [
      "Professionalism and integrity in line with organisation values",
      "Planning and organization",
      "Strategic thinking skills",
      "Commercial  acumen",
      "Communication and interpersonal skills",
      "Ability to effectively manage multiple stakeholders",
      "Tact and diplomacy",
      "Ability to manage and drive change.",
    ],
    Contacts: [
      {
        Id: 1,
        JobId: 1,
        Name: "Brian D’Souza",
        Telephone: "+254 (0) 709 576 132",
        Email: "briandesouza@kpmg.co.ke",
      },
      {
        Id: 2,
        JobId: 1,
        Name: "Associate Director, Transformation - People and Change",
        Telephone: "+254 (0) 709 576 688",
        Email: "titilopeolajide@kpmg.co.ke",
      },
      {
        Id: 3,
        JobId: 1,
        Name: "Hilda Amahundu",
        Telephone: "+254 (0) 709 576 448",
        Email: "hamahundu@kpmg.co.ke",
      },
    ],
  },
  {
    Id: 7,
    Title: "Head, HR services ",
    EmpType: "Full time, permanent or contract ",
    DirectReport: "Chief Human  Resources Officer",
    ProfileWithinOrg: " ",
    Location: "Nairobi, Kenya ",
    RoleDetails: [
      "Our client, a reputable financial institution within the region, is looking for a forward-thinking and experienced individual to fill the role of Head, HR Services.",
      "The ideal candidate will be experienced in all aspects of HR administration, operations and transactions management, including maintenance of people records, employee welfare, employee relations, and wellness programs from a total reward perspective.",
      "Job purpose",
      "Reporting to the CHRO, the role holder will be responsible for effective and efficient running of all HR transactional / operational activities covering the areas highlighted above.",
      "The role holder will also be:",
      "Vast in the use of leading practice technology solutions to support delivery of transactional aspects of HR services, be able to effectively leverage analytics and be comfortable with data.",
      "Responsible for administration of employee welfare and wellness programs and associated funds, as well as certain aspects of front desk management",
    ],
    Responsibilities: [
      "Provide input into the development/ articulation of the organization’s people strategy and play a critical role in its delivery and implementation;",
      "Continuously identify business challenges stemming out of own area and champion the use of data to influence changes to operations, process or policy for the HR function;",
      "Ensure an adequate mechanism exists for the collection, processing and analysis of people data in line with applicable legal requirements around records retention, privacy, confidentiality, access, etc.",
      "Participate in the promotion of data governance and stewardship within the HR function in order to improve strategic and operational performance and insight;",
      "Responsible for management, administration, periodic review and upgrade (where required) of the Human Resource Information System (HRIS);",
      "Collaborate with other HRIS users to ensure integrity of the HRIS and advise management on organizational policy matters related to the HRIS;",
      "Responsible for developing a winning strategy for the management of staff welfare, employee relations, reward, benefits administration; etc. to foster exceptional employee experience as well as boost productivity;",
      "Identify leading practices in welfare management, benchmark the organization’s policies and practices against these and periodically champion the implementation of improvement initiatives subject to Management’s approval;",
      "Perform other duties as assigned by the CHRO in line with agreed delegation matrix.",
    ],
    AcademicQualifications: [
      "A Bachelor’s degree in the humanities, social sciences, human resource management or any other related field.",
      "A Master’s degree in strategic human resource management, organization development, business administration, etc. from a reputable institution will be an added advantage.",
      "Membership with relevant local, regional or global professional bodies is required.",
    ],
    ExperienceRequirements: [
      "Eight to twelve years’ experience in strategic human resource management in dynamic and complex organizational environment is key. Emphasis will be placed on experience relating to managing complex HR operations.",
      "At least three years in career history must be in a similar role in terms of scale and complexity.",
    ],
    Competencies: [
      "Demonstrable knowledge of and exposure to all aspects of human resource management along the employee lifecycle.",
      "Broad knowledge and experience in HR operations, HR shared services management, resourcing, reward and benefits administration, organization development, change management, employee experience management, etc. is required.",
      "Understanding of applicable laws and regulations.",
      "Demonstrable experience in articulating HR services strategy and managing its implementation.",
      "Extensive experience working with big data from a people perspective is critical.",
      "Ability to effectively leverage data to present insights is also key.",
      "Familiarity with standard HRIS.",
      "Exceptional coordination and organizational skills is critical for this role",
    ],
    Behaviours: [
      "Professionalism and integrity in line with organisation values",
      "Planning and organization",
      "Strategic thinking skills",
      "Commercial acumen",
      "Communication and interpersonal skills",
      "Strong execution skills",
      "Ability to effectively manage multiple stakeholders",
      "Tact and diplomacy",
      "Ability to manage and drive change",
    ],
    Contacts: [
      {
        Id: 1,
        JobId: 1,
        Name: "Brian D’Souza",
        Telephone: "+254 (0) 709 576 132",
        Email: "briandesouza@kpmg.co.ke",
      },
      {
        Id: 2,
        JobId: 1,
        Name: "Associate Director, Transformation - People and Change",
        Telephone: "+254 (0) 709 576 688",
        Email: "titilopeolajide@kpmg.co.ke",
      },
      {
        Id: 3,
        JobId: 1,
        Name: "Hilda Amahundu",
        Telephone: "+254 (0) 709 576 448",
        Email: "hamahundu@kpmg.co.ke",
      },
    ],
  },
  {
    Id: 9,
    Title: "Head of Talent Development",
    EmpType: "Full time, permanent or contract",
    DirectReport: "Chief Human  Resources Officer",
    ProfileWithinOrg: " ",
    Location: "Nairobi, Kenya ",
    RoleDetails: [
      "Our client, a reputable financial institution within the region, is looking for a forward-thinking and experienced individual as the Head of Talent Development.",
      "The ideal candidate will be an experienced talent management professional vast in the use of relevant data to provide leading practice talent development programmes and initiatives covering but not limited to learning, competency management, performance management and succession planning.",
      "Job purpose",
      "Reporting to the CHRO, the role holder will design and have responsibility for implementing targeted people development initiatives and programmes to continuously up-skill staff in line with the highly dynamic skill requirements of the industry",
      "The role holder will also be responsible for strategies and initiatives focused broadly on learning and leadership development as well as performance management and employee productivity; while leveraging on leading practice methods and tools.",
    ],
    Responsibilities: [
      "Develop and ensure the implementation of strategic talent development programs and plans in support of the organization’s strategy. The aim of this will be to support the overall development of capability within the organisation.",
      "Provide key input to the articulation and update of the organization’s people strategy/ agenda.",
      "Ensure a framework exists to analyse and monitor implementation of learning programmes within the organization to drive effectiveness.",
      "Oversee and be responsible for the process of competency management within the organization and ensure the right linkages to resourcing plans (i.e. recruitment and re-deployment plans); performance management, succession management, etc.",
      "Manage the talent database for the organization to ensure clarity on the talent pool and how it is evolving. This will provide good insight into the effectiveness of other HR programmes and initiatives.",
      "Provide oversight of the performance management process within the organization to ensure consistent implementation of agreed principles.",
      "Ensure consistent availability of the required data to make for an objective performance management process.",
      "Ensure the performance management process is periodically reviewed to drive increasing employee productivity.",
      "Focus on continuously building supervisor and line manager capability with respect to performance management to ensure the outcomes are reliable with respect to other HR levers such as career management, reward administration, etc.",
      "Contribute to strategic projects with other members of the HR team particularly where these impact Performance Management or Talent, Learning and Organisation Development’s processes and systems.",
      "Perform other duties as assigned by the CHRO in line with agreed delegation matrix.",
    ],
    AcademicQualifications: [
      "A Bachelor’s degree in the humanities, social sciences, human resource management or any other relevant discipline.",
      "A Master’s degree in strategic human resource management, organization design, business administration or any other relevant area from a reputable institution will be an added advantage.",
      "Full membership with relevant local, regional or global professional bodies is required.",
    ],
    ExperienceRequirements: [
      "Eight to twelve years’ experience in strategic human resource management in dynamic and complex organizational environment is key. While a broad base experience in HR is required, experience in talent management is key.",
      "At least three years in career history must be in a similar role in terms of scale and complexity.",
    ],
    Competencies: [
      "Demonstrable knowledge of and exposure to relevant aspects of human resource management along the employee lifecycle.",
      "Broad knowledge and experience in resourcing, succession management, competency models, reward management, learning and leadership development, performance management, etc.",
      "Understanding of applicable laws and regulations.",
      "Ability to effectively leverage data to present insights.",
      "Familiarity with leading practice ERP solutions, particularly is it relates to people management.",
    ],
    Behaviours: [
      "Professionalism and integrity in line with organisation values",
      "Planning and organization",
      "Strategic thinking skills",
      "Commercial acumen",
      "Communication and interpersonal skills",
      "Ability to effectively manage multiple stakeholders",
      "Tact and diplomacy",
      "Ability to manage and drive change.",
    ],
    Contacts: [
      {
        Id: 1,
        JobId: 1,
        Name: "Brian D’Souza",
        Telephone: "+254 (0) 709 576 132",
        Email: "briandesouza@kpmg.co.ke",
      },
      {
        Id: 2,
        JobId: 1,
        Name: "Associate Director, Transformation - People and Change",
        Telephone: "+254 (0) 709 576 688",
        Email: "titilopeolajide@kpmg.co.ke",
      },
      {
        Id: 3,
        JobId: 1,
        Name: "Hilda Amahundu",
        Telephone: "+254 (0) 709 576 448",
        Email: "hamahundu@kpmg.co.ke",
      },
    ],
  },
];

export default jobs;
