const GLOBAL_CONSTANTS = {
  signinUserSuccess: "USER HAS SIGNED IN",
  signinUserError: "USER SIGNIN FAILED",
  signinUserRequested: "USER SIGNIN Requested",
  signupUserSuccess: "USER SIGNIN SUCCESS",
  signupUserError: "USER SIGNIN FAILED",
  signupUserRequested: "USER SIGNUP REQUESTED",
  clearErrorMessageSuccess: "CLEAR ERROR MESSAGE SUCCESS",
  clearSuccessMessageSuccess: "CLEAR SUCCESS MESSAGE SUCCESS",
  authenticateUserWithGoogleSuccess: "AUTHENTICATE USER WITH GOOGLE SUCCESS",
  logoutSuccess: "LOGOUT WAS SUCCESFUL",
  createNotificationSuccess: "CREATE NOTIFICATION SUCCESS",
  updateProfileSuccess: "UPDATE PROFILE SUCCESS",
  updateProfileError: "UPDATE PROFILE ERROR",
  updateProfileRequested: "UPDATE PROFILE REQUESTED",
  getProfileSuccess: "GET PROFILE SUCCESS",
  getProfileRequested: "GET PROFILE REQUESTED",
  getProfileError: "GET PROFILE FAILED",
  uploadDocumentSuccess: "UPLOAD DOCUMENT SUCCESS",
  uploadDocumentError: "UPLOAD DOCUMENT ERROR",
  uploadDocumentRequested: "UPLOAD DOCUMENT REQUESTED",
  getUserApplicationsSuccess: "GET USER APPLICATIONS SUCCESS",
  getUserApplicationsError: "GET USER APPLICATIONS ERROR",
  getUserApplicationsRequested: "GET USER APPLICATIONS REQUESTED",
  checkLoggedInUserSuccess: "CHECK LOGGED IN USER SUCCESS",
  displayANewFormViewSuccess: "DISPLAY A NEW VIEW SUCCESFUL"
};
export default GLOBAL_CONSTANTS;
